accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('<str:username>/',views.profile, name='profile'),
    path('<str:username>/follow/',views.follow, name='follow'),
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),

    path('create/', views.create, name='create'),
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/like-async/', views.like_async, name='like_async'),

    path('<int:post_id>/delete/', views.post_delete, name='post_delete'), 
    path('<int:post_id>/comment/<int:id>/delete', views.comment_delete, name='comment_delete'),

    path('<int:post_id>/detail/', views.detail, name='detail'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField

# Create your models here.

class User(AbstractUser):
    profile_image = ResizedImageField(
        size=[500,500],
        crop=['middle', 'center'],
        upload_to='profile/'
    )
    # post_set = 
    # like_posts = 

    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)
    # followers = 

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.

class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # image = models.ImageField(upload_to='image/%Y/%m')
    image = ResizedImageField(
        size=[500,500],
        crop=['middle', 'center'],
        upload_to='image/%Y/%m'
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user_id = 

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
    post  = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        # model = User
        model = get_user_model()
        fields = ('username', 'profile_image',)

class CustomAuthenticationForm(AuthenticationForm):
    pass

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        exclude = ('user','like_users',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('accounts:login')

    else:
        form = CustomUserCreationForm()

    context = {
        'form': form
    }

    return render(request, 'accounts/form.html', context)

def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request,request.POST)

        if form.is_valid():
            user = form.get_user()
            auth_login(request,user)

            return redirect('posts:index')

    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

def profile(request, username):
    User = get_user_model()

    user_info = User.objects.get(username=username)

    posts = user_info.post_set.all().order_by('-created_at')
    # posts = Post.objects.get(user_id=user_info.id)
    # posts = user_info.post_set.all()


    context ={
        'user_info': user_info,
        'posts': posts,
    }

    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, username):
    User = get_user_model()

    me = request.user
    you = User.objects.get(username=username)

    # 팔로잉이 이미 되어있는 경우
    if me in you.followers.all():
        you.followers.remove(me)
    # if you in me.followings.all():
    #     me.followings.remove(you)

    # 팔로잉이 아직 안 된 경우
    else:
        me.followings.add(you)

    return redirect('accounts:profile', username=username)

@login_required
def logout(request):
    auth_logout(request)

    return redirect('posts:index')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.

def index(request):
    posts = Post.objects.all().order_by('-id')
    comment_form = CommentForm()

    context = {
        'posts': posts,
        'comment_form': comment_form,
    }

    return render(request, 'index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')

    else:
        form = PostForm()

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

@login_required
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user= request.user

        post = Post.objects.get(id=post_id)
        comment.post = post

        # comment.post_id = post_id

        comment.save()

        if 'detail' in request.META.get('HTTP_REFERER'):
            return redirect('posts:detail', post_id=post_id)

        else:
            return redirect('posts:index')

@login_required
def like(request, post_id):
    user = request.user
    post = Post.objects.get(id=post_id)

    # 이미 좋아요 버튼을 누른 경우
    if user in post.like_users.all():
        post.like_users.remove(user)
    # if post in user.like_posts.all():
    #     user.like_posts.remove(post)

    # 좋아요 버튼을 아직 안 누른 경우
    else:
        post.like_users.add(user)
        # user.like_posts.add(post)
        


    return redirect('posts:index')


def like_async(request, post_id):
    # context = {
    #     'message': post_id,
    # }

    user = request.user
    post = Post.objects.get(id=post_id)
    
    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False
    else:
        post.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(post.like_users.all())
    }

    return JsonResponse(context)

def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)

    username = request.user

    post.delete()

    if 'detail' in request.META.get('HTTP_REFERER'):
        return redirect('accounts:profile', username=username)

    else:
        return redirect('posts:index')


def comment_delete(request, post_id, id):
    comment = Comment.objects.get(id=id)
    
    comment.delete()

    if 'detail' in request.META.get('HTTP_REFERER'):
        return redirect('posts:detail', post_id=post_id)

    else:
        return redirect('posts:index')


def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()

    context = {
        'post': post,
        'comment_form': comment_form,
    }

    return render(request, 'detail.html', context)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
<h1>signup</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div class="row">
    <div class="col-4">
        <img src="{{user_info.profile_image.url}}" alt="" class="img-fluid rounded-circle" width="200px">
    </div>
    <div class="col-8">
        <div class="row">
            <div class="col-3 proname">{{user_info.username}}</div>
            <!-- user : 로그인한 사람 / user_info : profile 계정 유저 -->
            {% if user != user_info %}
            <div class="col-4">
                {% if user in user_info.followers.all %}
                <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-primary btn-sm">팔로잉</a>
                {% else %}
                <a href="{% url 'accounts:follow' username=user_info.username %}"
                    class="btn btn-secondary btn-sm">팔로우</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col pro">게시물 {{user_info.post_set.all|length}}</div>
            <div class="col pro">팔로워 {{user_info.followers.all|length}}</div>
            <div class="col pro">팔로우 {{user_info.followings.all|length}}</div>
        </div>
    </div>
</div>
<br>

<div class="row row-cols-3">
    {% for post in posts %}
    <a href="{% url 'posts:detail' post_id=post.id%}">
        <div class="col">
            <div class="card rounded-0">
                <img src="{{post.image.url}}" alt="">
            </div>
        </div>
    </a>
    {% endfor %}
</div>

{% endblock %}

posts/templates/_card.html
{% load bootstrap5 %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div class="card" style="width: 18rem;">
    <div class="card-header">
        <p>
            <img src="{{post.user.profile_image.url}}" class="rounded-circle"  width="40px" alt="">
            <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{post.user}}</a>
        </p>
    </div>
    <img src="{{post.image.url}}" alt="...">

    <div class="card-body">
        <!-- <a href="{% url 'posts:like' post_id=post.id %}" class="text-reset text-decoration-none" > -->
        {% if post in user.like_posts.all %}
            <i class="bi bi-heart-fill heart" style="color: red" data-post-id="{{post.id}}" > {{post.like_users.all|length}}</i> 
        {% else %}
            <i class="bi bi-heart heart" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i> 
        {% endif %} 
        <!-- </a>  -->
        <!-- {{post.like_users.all|length}} -->
        명이 좋아합니다.

        <p class="card-text">{{post.content}}</p>
        <p class="card-text oneline">{{post.created_at|timesince}}</p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        {% if user == post.user %}
            <a href="{% url 'posts:post_delete' post_id=post.id %}"
            class="text-reset text-decoration-none btn btn-light btn-sm oneline right" 
            style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">삭제</a>
        {% endif %}
    </div>

    <div class="card-footer">
        {% if user.is_authenticated %}
            <form action="{% url 'posts:comment_create' post_id=post.id %} " method="POST" class="commentform">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                <input type="submit">
            </form>
            <hr>
        {% endif %}

        {% for comment in post.comment_set.all %}
            <li style="list-style: none;">
            <img src="{{comment.user.profile_image.url}}" class="rounded-circle" width="30px" alt="" style="display: inline;">
            {{comment.user}} : {{comment.content}}
            {% if comment.user == user %}
                <a href="{% url 'posts:comment_delete' post_id=post.id id=comment.id %}?next=/index/"
                class="text-reset text-decoration-none btn btn-outline-secondary right"
                style="--bs-btn-padding-y: .125rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">삭제</a>
            {% endif %}
            </li>
        {% endfor %}
    </div>
</div>

posts/templates/_detailcard.html
{% load bootstrap5 %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">


<div class="row row-cols-1 row-cols-md-2 g-4">

    <div class="col">
        <div class="card rounded-0">
            <img src="{{post.image.url}}" alt="...">
        </div>
    </div>

    <div class="col">
        <div class="card">
            <div class="card-header">
                <p style="display: inline;">
                    <img src="{{post.user.profile_image.url}}" class="rounded-circle oneline" width="40px" alt=""
                        style="display: inline;">
                <p style="display: inline;"></p>{{post.user}}</p>
                </p>
            </div>
            <div class="card-body">
                <p class="card-text" style="display: inline;">
                    <img src="{{post.user.profile_image.url}}" class="rounded-circle" width="40px" alt=""
                        style="display: inline;">
                <p style="display: inline;">{{post.content}}</p>
                <p class="right" style="display: inline;">{{post.created_at|timesince}}</p>
                </p>
                {% if user == post.user %}
                <a href="{% url 'posts:post_delete' post_id=post.id %}"
                    class="text-reset text-decoration-none btn btn-light btn-sm oneline right"
                    style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">삭제</a>
                {% endif %}
            </div>
            <hr>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% for comment in post.comment_set.all %}
                    <li class="list-group-item" style="list-style: none;">
                        <img src="{{comment.user.profile_image.url}}" class="rounded-circle" width="30px" alt=""
                            style="display: inline;">
                        {{comment.user}} : {{comment.content}}
                        {% if comment.user == user %}
                        <a href="{% url 'posts:comment_delete' post_id=post.id id=comment.id %}?next=/detail/"
                            class="text-reset text-decoration-none btn btn-outline-secondary right"
                            style="--bs-btn-padding-y: .125rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">삭제</a>
                        {% endif %}
                        <p class="right">{{comment.created_at|timesince}}</p>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="card-footer">
                {% if post in user.like_posts.all %}
                <i class="bi bi-heart-fill heart" style="color: red" data-post-id="{{post.id}}">
                    {{post.like_users.all|length}}</i>
                {% else %}
                <i class="bi bi-heart heart" data-post-id="{{post.id}}">{{post.like_users.all|length}}</i>
                {% endif %}
                명이 좋아합니다.
            </div>
            <form action="{% url 'posts:comment_create' post_id=post.id %} " method="POST" class="commentform">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                <input type="submit">
            </form>
        </div>
    </div>

</div>

posts/templates/detail.html
{% extends 'base.html' %}

{% block body %}

{% include '_detailcard.html' %}

<script>
    const likeButtons = document.querySelectorAll('i.heart')
    // console.log(likeButtons)

    likeButtons.forEach((likeButton) => {
        // console.log(likeButton)
        likeButton.addEventListener('click',(event) => {
            let postId = event.target.dataset.postId
            // console.log(postId)

            likeRequest(event.target, postId)
        })
    })

    let likeRequest = async (button, postId) => {
        console.log(button, postId)
        // django 서버에 요청을 보낸다
        let likeURL = `/posts/${postId}/like-async/`
        let response =  await fetch(likeURL)
        let result = await response.json()

        console.log(result)

        // django 서버의 응답에 따라 좋아요 버튼을 수정한다
        if (result.status) {
            // true : 좋아요가 눌린 경우
            button.classList.remove('bi-heart')
            button.classList.add('bi-heart-fill')
            button.style.color = 'red'
            button.innerHTML = result.count
        } else {
            // false : 좋아요 취소
            button.classList.remove('bi-heart-fill')
            button.classList.add('bi-heart')
            button.style.color = 'black'
            button.innerHTML = result.count
        }
    }

</script>

{% endblock %}

posts/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}

{% block body %}

    {% for post in posts %}
        {% include '_card.html' %}
    {% endfor %}


    <script>
        const likeButtons = document.querySelectorAll('i.heart')
        // console.log(likeButtons)

        likeButtons.forEach((likeButton) => {
            // console.log(likeButton)
            likeButton.addEventListener('click',(event) => {
                let postId = event.target.dataset.postId
                // console.log(postId)

                likeRequest(event.target, postId)
            })
        })

        let likeRequest = async (button, postId) => {
            console.log(button, postId)
            // django 서버에 요청을 보낸다
            let likeURL = `/posts/${postId}/like-async/`
            let response =  await fetch(likeURL)
            let result = await response.json()

            console.log(result)

            // django 서버의 응답에 따라 좋아요 버튼을 수정한다
            if (result.status) {
                // true : 좋아요가 눌린 경우
                button.classList.remove('bi-heart')
                button.classList.add('bi-heart-fill')
                button.style.color = 'red'
                button.innerHTML = result.count
            } else {
                // false : 좋아요 취소
                button.classList.remove('bi-heart-fill')
                button.classList.add('bi-heart')
                button.style.color = 'black'
                button.innerHTML = result.count
            }
        }

    </script>

{% endblock %}

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'posts:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'posts:create' %}">Create</a>
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
        {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'accounts:profile' username=user %}">{{user}}</a>
        {% endif %}
    </div>
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>

    {% include '_nav.html' %}

    <div class="container">
        {% block body %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>